# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runway < Formula
  desc "The runway CLI."
  homepage "https://runway.planetary-quantum.com/"
  version "1.13.0"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.runway.horse/runway/1.13.0/runway_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "26877a849901020eef7c4b58e7a36f37dc91496935df80cdcb7486d718ba97bf"

      def install
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.runway.horse/runway/1.13.0/runway_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1b2f6af22dd98ea668a8698dd5e5e042af71558f75117f1c83ad0328e718d2c0"

      def install
        bin.install "runway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://download.runway.horse/runway/1.13.0/runway_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "d0b0570c33c6122260c378a05e0f755e0a9e30f09bcc707426d6ba93177267bf"

        def install
          bin.install "runway"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://download.runway.horse/runway/1.13.0/runway_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "6b8f213b815c83895a0ea4521dacf17861990431fa1f9ac7211e2f08a5396841"

        def install
          bin.install "runway"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run `runway login` to get started, and `runway install-completions` to install auto-complete
    EOS
  end

  test do
    system "#{bin}/runway version"
  end
end
