# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runway < Formula
  desc "The runway CLI."
  homepage "https://runway.planetary-quantum.com/"
  version "1.7.2"
  license "proprietary"

  on_macos do
    on_intel do
      url "https://download.runway.horse/runway/1.7.2/runway_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e5e9116971b0a328a7f5126612539f516fcf64b268a9c82af65f2a94d0242426"

      def install
        bin.install "runway"
      end
    end
    on_arm do
      url "https://download.runway.horse/runway/1.7.2/runway_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fda24effb6cb09f8f35d77bdd995aba8e40be22aacfa202af86f2916d69309a0"

      def install
        bin.install "runway"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://download.runway.horse/runway/1.7.2/runway_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "712efca62da0f22f0363728597be3a42c9cfe09fa34887e63673cf085ba9cdaf"

        def install
          bin.install "runway"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://download.runway.horse/runway/1.7.2/runway_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "0b4b0651968417e7806ddc05eb445faf6baffe94fe1760bcf93e1991f9ebb5c4"

        def install
          bin.install "runway"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run `runway login` to get started, and `runway install-completions` to install auto-complete
    EOS
  end

  test do
    system "#{bin}/runway version"
  end
end
