# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runway < Formula
  desc "The runway CLI."
  homepage "https://runway.planetary-quantum.com/"
  version "1.11.0"
  license "proprietary"

  on_macos do
    on_intel do
      url "https://download.runway.horse/runway/1.11.0/runway_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5aa6415bd6800ec1a05364522d269144693f164e8f0cefff5e84c13f32bac6ba"

      def install
        bin.install "runway"
      end
    end
    on_arm do
      url "https://download.runway.horse/runway/1.11.0/runway_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d7dfbac8c088c1caca6d7453887f686d972c79222b63afbbce36a38e7ee48f57"

      def install
        bin.install "runway"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://download.runway.horse/runway/1.11.0/runway_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "0bea9e733083096fb283a46f25a8ea67fd569845b71749ccde5c00e3134e17a3"

        def install
          bin.install "runway"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://download.runway.horse/runway/1.11.0/runway_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "1b5a54dd4fc928375332beff16bc80a1647476159b02023eb9025b93e9fecccd"

        def install
          bin.install "runway"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run `runway login` to get started, and `runway install-completions` to install auto-complete
    EOS
  end

  test do
    system "#{bin}/runway version"
  end
end
