# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runway < Formula
  desc "The runway CLI."
  homepage "https://runway.planetary-quantum.com/"
  version "1.4.3"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.runway.horse/runway/1.4.3/runway_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "dd059c9dd9eb2bbd456684cffdb5a8cc920455c43f9b5ec448d219ec38c133df"

      def install
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.runway.horse/runway/1.4.3/runway_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6fcc62adbe590417e681673f03f9453b8c43ffb7cdaa33653c7bdf3db9252881"

      def install
        bin.install "runway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://download.runway.horse/runway/1.4.3/runway_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "30cb43f26c776a60760e58f58f04c7cf31d895efb035ce35d69bab712856d0d6"

      def install
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.runway.horse/runway/1.4.3/runway_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ed92aa22e85a2f0c672106d3dd203c82cfc46442ad37135ee32f96efb8613ee4"

      def install
        bin.install "runway"
      end
    end
  end

  def caveats
    <<~EOS
      Run `runway login` to get started, and `runway install-completions` to install auto-complete
    EOS
  end

  test do
    system "#{bin}/runway version"
  end
end
