# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runway < Formula
  desc "The runway CLI."
  homepage "https://runway.planetary-quantum.com/"
  version "1.37.1"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.runway.horse/runway/1.37.1/runway_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cbc378a0043aa320a2f01e8fdd5a9b78d4bb39cf5bcc8c28ddbc29dea1ffbbfd"

      define_method(:install) do
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.runway.horse/runway/1.37.1/runway_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9d9cb5186eaff51af551515888cccc1670bc02c0c885834bcbd2b7500d96eafc"

      define_method(:install) do
        bin.install "runway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://download.runway.horse/runway/1.37.1/runway_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d1334a0b6a59ae47c59e844e3e138306ae1feadf097935c0ee2069d0e7cbbe07"
      define_method(:install) do
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.runway.horse/runway/1.37.1/runway_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "10236d888a2051a9fd13b93adac2cf5cd480d55e33d29f96c2460862be2316db"
      define_method(:install) do
        bin.install "runway"
      end
    end
  end

  def caveats
    <<~EOS
      Run `runway login` to get started, and `runway install-completions` to install auto-complete
    EOS
  end

  test do
    system "#{bin}/runway version"
  end
end
