# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runway < Formula
  desc "The runway CLI."
  homepage "https://runway.planetary-quantum.com/"
  version "1.36.0"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.runway.horse/runway/1.36.0/runway_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "23362dbf15207eb184e5926e14d9e9b2beed04940ed75f77f807ff1e5f492d86"

      define_method(:install) do
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.runway.horse/runway/1.36.0/runway_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "37e084ffc20dd3b574ceab1b4855498a4796b8c2ab577b3cc9ff4418007fb259"

      define_method(:install) do
        bin.install "runway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://download.runway.horse/runway/1.36.0/runway_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3270c2d4281c2e4f9b761a628eb8d38e8348466898db46071e6e7e96df6b3f3f"
      define_method(:install) do
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.runway.horse/runway/1.36.0/runway_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f2fb45e3d68c8b4ffcb0bd53460b7ce1a97c727d1097b688d67791061d36b73"
      define_method(:install) do
        bin.install "runway"
      end
    end
  end

  def caveats
    <<~EOS
      Run `runway login` to get started, and `runway install-completions` to install auto-complete
    EOS
  end

  test do
    system "#{bin}/runway version"
  end
end
